# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Vaccine.create(name: "B型肝炎（１回目）", kind_id: 0)
Vaccine.create(name: "B型肝炎（２回目）", kind_id: 0)
Vaccine.create(name: "B型肝炎（３回目）", kind_id: 0)
Vaccine.create(name: "ロタウイルス（１回目）", kind_id: 2)
Vaccine.create(name: "ロタウイルス（２回目）", kind_id: 2)
Vaccine.create(name: "ロタウイルス（３回目）", kind_id: 2)
Vaccine.create(name: "ヒブ（１回目）", kind_id: 0)
Vaccine.create(name: "ヒブ（２回目）", kind_id: 0)
Vaccine.create(name: "ヒブ（３回目）", kind_id: 0)
Vaccine.create(name: "ヒブ（４回目）", kind_id: 0)
Vaccine.create(name: "小児用肺炎球菌（１回目）", kind_id: 0)
Vaccine.create(name: "小児用肺炎球菌（２回目）", kind_id: 0)
Vaccine.create(name: "小児用肺炎球菌（３回目）", kind_id: 0)
Vaccine.create(name: "小児用肺炎球菌（４回目）", kind_id: 0)
Vaccine.create(name: "四種混合（１回目）", kind_id: 0)
Vaccine.create(name: "四種混合（２回目）", kind_id: 0)
Vaccine.create(name: "四種混合（３回目）", kind_id: 0)
Vaccine.create(name: "四種混合（４回目）", kind_id: 0)
Vaccine.create(name: "BCG（１回目）", kind_id: 1)
Vaccine.create(name: "麻しん・風しん（１回目）", kind_id: 1)
Vaccine.create(name: "麻しん・風しん（２回目）", kind_id: 1)
Vaccine.create(name: "水ぼうそう（１回目）", kind_id: 1)
Vaccine.create(name: "水ぼうそう（２回目）", kind_id: 1)
Vaccine.create(name: "日本脳炎（１回目）", kind_id: 0)
Vaccine.create(name: "日本脳炎（２回目）", kind_id: 0)
Vaccine.create(name: "日本脳炎（３回目）", kind_id: 0)
Vaccine.create(name: "日本脳炎（４回目）", kind_id: 0)
Vaccine.create(name: "HPV（１回目）", kind_id: 0)
Vaccine.create(name: "HPV（２回目）", kind_id: 0)
Vaccine.create(name: "HPV（３回目）", kind_id: 0)
